# Generated by Django 3.0.2 on 2020-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrogen_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrogram',
            name='timeframe_end',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='spectrogram',
            name='timeframe_start',
            field=models.IntegerField(default=0),
        ),
    ]
