# Generated by Django 3.0.2 on 2020-01-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrogen_main', '0002_auto_20200112_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrogram',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='spectrogram',
            name='image_file_path',
            field=models.FilePathField(null=True),
        ),
    ]
