# Generated by Django 3.0.2 on 2020-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrogen_main', '0003_auto_20200112_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrogram',
            name='image_file_path',
            field=models.FilePathField(default='/mnt/e/Python/TAIProject/spectrogen/spectrogen_main/media'),
        ),
    ]
