# Generated by Django 3.0.2 on 2020-01-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrogen_main', '0005_auto_20200112_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrogram',
            name='image_file',
            field=models.ImageField(null=True, upload_to='spectrograms'),
        ),
    ]
